apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace}}
spec:
  {{/*host: {{ .Values.network.apiHost }}*/}}
  port:
    targetPort:  {{.Values.network.portName}}
  to:
    kind: Service
    name: {{ .Chart.Name }}