apiVersion: v1
kind: Service
metadata:
  labels:
    template: mysql-ephemeral
  name: {{ .Values.db.host }}
  namespace: chuck
spec:
  selector:
    app: {{ .Chart.Name }}-mysql
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306

