apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: appmon-prometheus-operator
  serviceMonitorSelector:
    matchLabels:
      appmon: "service-yes"
  podMonitorSelector:
    matchLabels:
      appmon: "pod-yes"
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
