apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: appmon-prometheus
    role: alert-rules
  name: appmon-prometheus-example-rules
  namespace: chuck
spec:
  groups:
  - name: test-rule
    rules:
    - alert: HighErrorRate
      expr: sum(tomcat_global_error_total{job="chuck"}) > 1
      for: 1m
      labels:
        app: api
      annotations:
        description: "This is test prom rule for high error rate"