#apiVersion: monitoring.coreos.com/v1
#kind: ServiceMonitor
#metadata:
#  name: example-app-web-1
#  labels:
#    appmon: service-yes
#spec:
#  selector:
#    matchLabels:
#      appmon: service-yes
#  endpoints:
#  - port: http
#  - port: web
#---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scrape-chuck-ns
  namespace: chuck
  labels:
    appmon: service-yes
spec:
  namespaceSelector:
    any: false
    matchNames:
      - chuck
      - appmon
  selector:
    matchLabels:
      appmon: service-yes
  endpoints:
  - port: http
    path: "/actuator/prometheus"
  - port: web

