apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    appmon: service-yes
spec:
  selector:
    matchLabels:
      appmon: service-yes
  endpoints:
  - port: mysql
