apiVersion: v1
kind: Service
metadata:
  labels:
    appmon: service-yes
  name: mysql-db
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    name: mysql-db
